f = open(r"src\app\chefs\[slug]\page.tsx", "w", encoding="utf-8")
f.write("import { notFound } from \"next/navigation\"\n")
f.write("import { chefs } from \"../chefsData\"\n")
f.write("import ChefProfileClient from \"./ChefProfileClient\"\n")
f.write("export function generateStaticParams() { return chefs.map(c => ({ slug: c.slug })) }\n")
f.write("export default async function ChefPage({ params }) {\n")
f.write("  const { slug } = await params\n")
f.write("  const chef = chefs.find(c => c.slug === slug)\n")
f.write("  if (!chef) notFound()\n")
f.write("  const i = chefs.findIndex(c => c.slug === slug)\n")
f.write("  const prev = i > 0 ? chefs[i-1] : null\n")
f.write("  const next = i < chefs.length-1 ? chefs[i+1] : null\n")
f.write("  return <ChefProfileClient chef={chef} prevChef={prev} nextChef={next} allChefs={chefs} />\n")
f.write("}\n")
f.close()
print("done")
