f = open("src/app/layout.tsx", "r", encoding="utf-8", errors="ignore")
c = f.read()
f.close()
c = c.replace("import type { Metadata } from \"next\"", "import type { Metadata } from \"next\"\nimport { WhatsAppButton } from \"@/components/WhatsApp\"")
open("src/app/layout.tsx", "w", encoding="utf-8", newline="\n").write(c)
print("layout done")
f = open("src/app/page.tsx", "r", encoding="utf-8", errors="ignore")
c = f.read()
f.close()
c = c.replace("info@kitchenthree.co", "kitchenthreecairo@gmail.com")
open("src/app/page.tsx", "w", encoding="utf-8", newline="\n").write(c)
print("email done")
f = open("src/components/Footer.tsx", "r", encoding="utf-8", errors="ignore")
c = f.read()
f.close()
c = c.replace("info@kitchenthree.co", "kitchenthreecairo@gmail.com")
open("src/components/Footer.tsx", "w", encoding="utf-8", newline="\n").write(c)
print("footer done")
