f = open("src/app/layout.tsx", "r", encoding="utf-8", errors="ignore")
c = f.read()
f.close()
c = c.replace("import \"./globals.css\"", "import \"./globals.css\"\nimport { WhatsAppButton } from \"@/components/Nav\"")
c = c.replace("<body>{children}</body>", "<body>{children}<WhatsAppButton /></body>")
f = open("src/app/layout.tsx", "w", encoding="utf-8")
f.write(c)
f.close()
print("done")
