lines = []
lines.append("import type { Metadata } from \"next\"")
lines.append("import \"./globals.css\"")
lines.append("import { WhatsAppButton } from \"@/components/WhatsApp\"")
lines.append("")
lines.append("export const metadata: Metadata = { title: { default: \"Kitchen Three | B2B Culinary Consultancy\", template: \"%s | Kitchen Three\" }, description: \"Egypt leading B2B culinary consultancy.\", robots: { index: true, follow: true }, alternates: { canonical: \"https://www.kitchenthree.co\" } }")
lines.append("")
lines.append("export default function RootLayout({ children }: { children: React.ReactNode }) {")
lines.append("  return (")
lines.append("    <html lang=\"en\">")
lines.append("      <head>")
lines.append("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />")
lines.append("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossOrigin=\"anonymous\" />")
lines.append("        <link href=\"https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap\" rel=\"stylesheet\" />")
lines.append("      </head>")
lines.append("      <body>")
lines.append("        {children}")
lines.append("        <WhatsAppButton />")
lines.append("      </body>")
lines.append("    </html>")
lines.append("  )")
lines.append("}")
open("src/app/layout.tsx", "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("done")
