import { notFound } from "next/navigation"
import ChefProfileClient from "./ChefProfileClient"

const chefs = [
  { slug: 'yann-bonneau', name: 'Yann Bonneau', country: 'France', title: 'Pastry Chef & International Consultant', photo: '/images/chefs/yann-bonneau.jpg', color: 'var(--teal)', bg: 'var(--teal-light)', credentials: ['Champion of Spain in Artistic Pastry Pieces', 'Co-founder, World Cup of Chocolatine', 'Head Chef, Chateau de la Messardiere age 21', 'Head Chef, 5-star hotel, Val d Isere'], bio: 'After completing his training in the finest Parisian patisseries, Yann moved to Saint Tropez to take his first position as head chef at age 21 at the Chateau de la Messardiere, a palace hotel. He became the pastry chef to the stars, then led the pastry team of a 5-star hotel in Val d Isere. He moved to Spain, opened five shops, and became Champion of Spain in artistic pieces. He co-founded the World Cup of Chocolatine in Toulouse, organizing it in China, Kazakhstan, Morocco, and Cameroon.', specialties: ['French Patisserie', 'Chocolate & Sugar Arts', 'Pastry Team Training', 'Product Development'], available: 'Masterclasses, product development, pastry team training', signatures: [] },
  { slug: 'enzo-bonneau', name: 'Enzo Bonneau', country: 'France', title: 'Michelin-Trained Pastry Chef & Consultant', photo: '/images/chefs/enzo-bonneau.jpg', color: 'var(--amber)', bg: 'var(--amber-light)', credentials: ['The Waterside Inn *** Michelin, England', 'La Dame de Pic ** Michelin, London', 'Hotel Arima ****, San Sebastian', '2nd Place Toque d Or Patisserie 2021, France'], bio: 'Enzo Bonneau, a French pastry chef born in 1997 in Toulouse, is renowned for his creativity and expertise in luxury hospitality. After training in Valencia, he honed his skills at The Waterside Inn (3 Michelin stars) and La Dame de Pic (2 Michelin stars, London). Since 2019, Enzo has worked as an international consultant, earning 2nd place at the 2021 Toque d Or Patisserie. He blends classic French techniques with global flavours and specialises in plated desserts.', specialties: ['Classical French Pastry', 'Plated Desserts', 'Fine Dining Consulting', 'Chef Mentorship'], available: 'Fine dining projects, menu development, chef training programs', signatures: [] },
  { slug: 'niko-koulousias', name: 'Niko Koulousias', country: 'Greece', title: 'Executive Chef & Royal Event Specialist', photo: '/images/chefs/niko-koulousias.jpg', color: 'var(--coral)', bg: 'var(--coral-light)', credentials: ['Chef at Prince Harry & Meghan Markle Royal Wedding 2018', 'Catered Queen Elizabeth 70th Platinum Jubilee', 'Best Chef in Northern Greece 2007', 'Co-founded Ghana Chef Association'], bio: 'In 2018, Greek chef Niko Koulousias was part of the team that crafted the menu for Prince Harry and Meghan Markle wedding, later catering Queen Elizabeth 70th Jubilee. He earned degrees from the New England Culinary Art Institute and has cooked for world leaders worldwide. He co-founded the Ghana Chef Association and linked Ducasse Education to establish a culinary school in Lebanon.', specialties: ['Mediterranean Cuisine', 'Royal & Diplomatic Events', 'Large-Scale Luxury Catering', 'Executive Consulting'], available: 'Luxury events, diplomatic catering, executive chef consultancy', signatures: [] },
  { slug: 'hadil-amasheh', name: 'Hadil Amasheh', country: 'Jordan / Egypt', title: 'F&B Entrepreneur & Culinary Consultant', photo: '/images/chefs/hadil-amasheh.jpg', color: 'var(--teal)', bg: 'var(--teal-light)', credentials: ['AUC Alumna - American University in Cairo', 'Goldman Sachs 10,000 Women Graduate', 'Member, Egyptian Chefs Association', 'Founder, Cookies N Pies - Zero-Waste Bakery'], bio: 'Hadeel Amasheh, a Jordanian entrepreneur and mother of two, moved to Cairo in 1988. A proud AUC alumna and Goldman Sachs 10,000 Women graduate, she spent over a decade in the culinary arts. In 2013, she launched Cookies N Pies, an eco-friendly zero-waste bakery that grew into a premium online bakery offering over 120 treats including gluten-free and vegan options.', specialties: ['Pastry & Bakery Arts', 'F&B Entrepreneurship', 'Sustainable Food Business', 'MENA Food Markets'], available: 'Business consulting, culinary education, F&B strategy', signatures: [] },
  { slug: 'gerard-livigni', name: 'Gerard Livigni', country: 'France', title: 'MOF Finalist & Master Baker', photo: '/images/chefs/gerard-livigni.jpg', color: 'var(--amber)', bg: 'var(--amber-light)', credentials: ['MOF Finalist 2011 - Meilleur Ouvrier de France', 'Head of Bakery Division, Apprentice Training Centre', 'International consultant promoting French baking globally', '30+ years in prestigious establishments'], bio: 'After completing his training as a baker, Gerard opened his own business and became a teacher at a training centre for apprentices, rising to head of the bakery division. In 2011, he was a finalist for the MOF - Meilleur Ouvrier de France, one of the most prestigious titles in French cuisine. He is now an international consultant promoting the art of French baking around the world.', specialties: ['French Artisan Baking', 'Bread & Viennoiserie', 'Kitchen Management', 'Team Training'], available: 'Bakery consulting, kitchen management, team training', signatures: [] },
  { slug: 'ramy-somoeil', name: 'Ramy Somoeil', country: 'Egypt', title: 'Mediterranean & Levantine Cuisine Expert', photo: '/images/chefs/ramy-somoeil.jpg', color: 'var(--coral)', bg: 'var(--coral-light)', credentials: ['20+ years mastering Lebanese, Italian & Mediterranean cuisines', 'Former General Chef, Raffaello & Abdel-Wahab', 'Trained at NileCity, Rossini, and Callistos Italy', 'Sous Chef, Babyl Restaurant'], bio: 'Chef Ramy Somoeil, a dedicated Egyptian chef, has spent over 20 years mastering Lebanese, Italian, and Mediterranean cuisines. A graduate of the Faculty of Tourism and Hotels, he refined his skills at NileCity, Rossini Restaurant, and Callistos in Italy, later leading teams as General Chef at Raffaello and Abdel-Wahab. Fluent in Arabic and Italian, Ramy delivers unforgettable fine-dining experiences.', specialties: ['Lebanese Cuisine', 'Mediterranean Cuisine', 'Italian Cuisine', 'Menu Development'], available: 'Menu development, kitchen training, cuisine consulting', signatures: [] },
  { slug: 'walid-karim', name: 'Walid Karim', country: 'Egypt', title: 'Pizza Master & Italian Cuisine Specialist', photo: '/images/chefs/walid-karim.jpg', color: 'var(--teal)', bg: 'var(--teal-light)', credentials: ['20+ years of pizza mastery', 'Former Chef, Mercato Italiano', 'Former Chef, Casper & Gambini', 'Graduate, Ain Shams University'], bio: 'Walid Karim is a seasoned pizza chef with over 20 years of experience. A graduate of Ain Shams University, Walid has mastered his craft at Mercato Italiano, Casper and Gambini, and Macaroni Grill. Known for his leadership and ability to thrive under pressure, he excels at mentoring new employees and delivering exceptional quality in every pizza he creates.', specialties: ['Neapolitan Pizza', 'Italian Cuisine', 'Dough Science', 'Pizzeria Concept Development'], available: 'Pizzeria concepts, kitchen training, product development', signatures: [] },
  { slug: 'giovani-mascari', name: 'Giovani Mascari', country: 'Italy', title: 'Executive Pizzaiolo & Innovation Chef', photo: '/images/chefs/giovani-mascari.jpg', color: 'var(--amber)', bg: 'var(--amber-light)', credentials: ['Creator of trademarked Sushi Pizza concept', 'Executive Pizzaiolo, Fratelli Panza - Udine', 'International speaker and culinary innovator', 'Originally from Palermo, Sicily'], bio: 'Chef Giovanni Mascari is an acclaimed Italian pizza chef from Palermo, known for his innovative approach and his signature creation: Sushi Pizza. As executive pizzaiolo at Fratelli Panza in Udine, he blends traditional Italian pizza-making with creative twists. His Sushi Pizza is now a registered trademark combining the aesthetics of sushi with the craft of pizza.', specialties: ['Fusion Pizza', 'Innovation Menus', 'Sushi Pizza', 'Concept Development'], available: 'Innovation concepts, fusion menus, executive training', signatures: [] },
  { slug: 'luca-montersino', name: 'Luca Montersino', country: 'Italy', title: 'Pastry Celebrity & F&B Empire Builder', photo: '/images/chefs/luca-montersino.jpg', color: 'var(--coral)', bg: 'var(--coral-light)', credentials: ['Italian television pastry personality & bestselling author', 'Founder - Golosi di Salute pastry lab, Alba', 'Culinary empire spanning Italy, Tokyo & New York', 'Pioneer of healthy gourmet desserts'], bio: 'Luca Montersino is a celebrated Italian pastry chef, visionary entrepreneur, and television sensation. Born in Turin in 1973, he revolutionised pastry by blending Italian tradition with cutting-edge creativity. As founder of the Golosi di Salute pastry lab in Alba, he pioneered healthy gourmet desserts. His culinary empire stretches from Italy to Tokyo and New York.', specialties: ['Italian Pastry', 'Healthy Gourmet Desserts', 'Brand Building', 'Pastry Education'], available: 'Brand development, pastry consulting, masterclasses', signatures: [] },
  { slug: 'luca-borgioli', name: 'Luca Borgioli', country: 'Italy', title: 'World Panettone Champion', photo: '/images/chefs/luca-borgioli.jpg', color: 'var(--teal)', bg: 'var(--teal-light)', credentials: ['Gold Medal - FIPGC World Panettone Championship 2020', 'Pastry Chef, Caffe Valiani - Pistoia', 'Laboratory Manager, Pasticceria Barbera - Signa', 'Specialist in pate a choux and leavened products'], bio: 'Luca Borgioli is an acclaimed Italian pastry chef renowned for his innovative approach to traditional Italian desserts, particularly pate a choux. He began in France immersing himself in French patisserie traditions. In 2020, he won the gold medal in the Innovative Panettone category at the FIPGC World Panettone Championship. He is celebrated for his modern reinterpretations of eclairs and bigne.', specialties: ['Panettone & Leavened Products', 'Artisan Italian Bakery', 'Pate a Choux', 'Bakery Consulting'], available: 'Bakery consulting, product development, masterclasses', signatures: [] },
]

export function generateStaticParams() {
  return chefs.map(c => ({ slug: c.slug }))
}

export default async function ChefPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const chef = chefs.find(c => c.slug === slug)
  if (!chef) notFound()
  const i = chefs.findIndex(c => c.slug === slug)
  const prev = i > 0 ? chefs[i - 1] : null
  const next = i < chefs.length - 1 ? chefs[i + 1] : null
  return <ChefProfileClient chef={chef} prevChef={prev} nextChef={next} allChefs={chefs} />
}
